# Site settings
title: Blog
name: yuebin
email: yuebin616@126.com
author: yuebin
url: http://yuebin.github.io
resume_site: http://yuebin.github.io
github: https://github.com/yuebin
baseurl: "/yuebin"
description: 
meta_description: 三叶虫;个人博客;好好学习天天向上。
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: yuebin616

# Build settings
markdown: kramdown
